--------------------------------------------------------
--  DDL for Table BESTFRIEND
--------------------------------------------------------

  CREATE TABLE "LATTEWORLD"."BESTFRIEND" 
   (	"BFNO" NUMBER(38,0), 
	"BFAPPLYID" VARCHAR2(150 BYTE), 
	"BFAPPLIEDID" VARCHAR2(150 BYTE), 
	"BFSTATUS" VARCHAR2(20 BYTE) DEFAULT 'H', 
	"BFCOMMENTS" VARCHAR2(500 BYTE), 
	"BFDATE" DATE, 
	"BFCONFIRMDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BESTFRIEND_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LATTEWORLD"."BESTFRIEND_PK" ON "LATTEWORLD"."BESTFRIEND" ("BFNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BESTFRIEND
--------------------------------------------------------

  ALTER TABLE "LATTEWORLD"."BESTFRIEND" MODIFY ("BFNO" NOT NULL ENABLE);
  ALTER TABLE "LATTEWORLD"."BESTFRIEND" ADD CONSTRAINT "BESTFRIEND_PK" PRIMARY KEY ("BFNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LATTEWORLD"."BESTFRIEND" MODIFY ("BFAPPLYID" NOT NULL ENABLE);
  ALTER TABLE "LATTEWORLD"."BESTFRIEND" MODIFY ("BFAPPLIEDID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BESTFRIEND
--------------------------------------------------------

  ALTER TABLE "LATTEWORLD"."BESTFRIEND" ADD CONSTRAINT "BESTFRIEND_FK1" FOREIGN KEY ("BFAPPLIEDID")
	  REFERENCES "LATTEWORLD"."USERINFO" ("USERID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "LATTEWORLD"."BESTFRIEND" ADD CONSTRAINT "BESTFRIEND_FK2" FOREIGN KEY ("BFAPPLYID")
	  REFERENCES "LATTEWORLD"."USERINFO" ("USERID") ENABLE;
